### PR TITLE
Instructions for container

### PR DESCRIPTION
**Pull request by alexlancaster**
Great instructions, thanks!  Would you able to refactor so the instructions as a new top-level section in DEV_NOTES.md?  I'm keeping the README.md for standard instructions and more dev-specific stuff goes there.  Then I can merge.

### CODE REVIEW

**Comment by akkornel** [comment]
The changes are mostly done, but for some reason my test results vary a bit from yours:

```
--- /pypop-source/singularity-test-data/USAFEL-UchiTelle-small-out.txt	2017-05-25 21:54:17.102883650 +0000
+++ USAFEL-UchiTelle-small-out.txt	2017-05-25 21:59:50.990883650 +0000
@@ -101,8 +101,8 @@
Dememorization steps: 2000
Number of Markov chain samples: 1000
Markov chain sample size: 1000
-Std. error: 0.00437
-p-value (overall): 0.8085
+Std. error: 0.004064
+p-value (overall): 0.8232
Individual genotype p-values found to be significant
Genotype (observed/expected) [Chen's pval] [diff pval]
@@ -190,12 +190,12 @@
Dememorization steps: 2000
Number of Markov chain samples: 1000
Markov chain sample size: 1000
-Std. error: 0.006863
-p-value (overall): 0.4707
+Std. error: 0.006703
+p-value (overall): 0.4783
Individual genotype p-values found to be significant
Genotype (observed/expected) [Chen's pval] [diff pval]
-0712:0102:  (2/0.400000) 0.0338* 0.0361*
+0712:0102:  (2/0.400000) 0.0307* 0.0340*
2.4. Guo and Thompson HardyWeinberg output (monte-carlo) [C]
@@ -243,7 +243,7 @@
Pairwise LD estimates
---------------------
Locus pair            D      D'        Wn   ln(L_1)   ln(L_0)         S # permu p-value
-A:C             0.02734 0.88530   0.77023    -36.04    -55.27     38.45       - -      
+A:C             0.02579 0.86447   0.78174    -36.04    -55.27     38.45       - -      
A:B             0.00000 0.00000      -nan    -26.51    -26.51      0.00       - -      
C:B             0.00000 0.00000      -nan    -32.10    -32.10      0.00       - -      
```

**Comment by alexlancaster** [comment]
Looking good, perhaps you can move:

      singularity-test-data -> data/singularity-test

I like to keep all the data input and output in that directory (eventually will probably refactor to have input and output files in separate directories), but for now keep them in ```data```

**Comment by akkornel** [comment]
OK, I've moved the data.

At this point, I'd say my work is pretty much done, as I'm at the point where I can build a container for Kazu to work with.

Regarding the failing test, you mentioned in email that some parts are supposed to be off a bit (because of the use of a random seed), but that one part was not supposed to be different.

For the part that's based off of a random seed, if you don't want to build in the ability to set a random seed on the command line, you can mask out the appropriate parts of the output.  I do that right now, masking out the run timestamp that is put into the output files.  I manually masked the timestamps in the reference data when I added them to the repository; lines 31-32 of `Singularity` are where I mask out the timestamps from the .txt and .xml files that are generated during testing.

For the parts of the test output which were not supposed to be different, I don't know enough of the subject matter to describe what's going on, so I can't do much there either.  Even though the tests fail, the container is still built, so it can be examined!

BTW, I have Singularity Hub auto-building a container every time I push.  You can see them here: https://singularity-hub.org/collections/165/

Once you merge in this PR, you can go to https://singularity-hub.org, log in with GitHub, and link your repo.  At that point, Singularity Hub will auto-build every time there is a push!

**Comment by alexlancaster** [comment]
Great, I don't know much about containers, so it'll be a good opportunity to learn!

**Pull request merged**
