### PR TITLE
Module refactor

### PR DESCRIPTION
**Pull request by alexlancaster**
Hi all,

It would be useful if you could both test the module-refactor branch.  I've update the code and cleaned this up a lot, to create a new cleaned-up codebase which will help new features and future bug fixes. From the command-line you just need to run:

```
git pull
git checkout module-refactor
```

For @sjmack and @gwebster, there is an additional dependency on MacOS on Python ```setuptools```, so you'll need to

```
sudo port install py-setuptools
```

(this is also reflected in the README.md)

Once it all looks like it's working, I'll merge with master.  Also running PyPop from an installation ```./setup.py install --user``` doesn't always work if the prefix is non-standard (see #10).  Currently I recommend only running locally from within a git checkout.

@akkornel @sjmack @gwebster

### CODE REVIEW

**Comment by sjmack** [comment]
Hi Alex,

I’m getting an odd error when I try to checkout the module-refactor branch (see below). Any idea what the multitude of working tree files named “PyPop” are? I can’t see them. The only thing in the path is the parent PyPop directory, which is not a git repo.

Thanks!

Steve 

:pypop sjmack$ git checkout module-refactor
error: The following untracked working tree files would be overwritten by checkout:
	PyPop
	PyPop
	PyPop
	PyPop
	PyPop
	PyPop
	PyPop
	PyPop
	PyPop
	PyPop
	PyPop
	PyPop
	PyPop
Please move or remove them before you can switch branches.
Aborting
:pypop sjmack$ pwd
/Applications/PyPop/pypop
:pypop sjmack$ ls
Arlequin.py			Homozygosity.py			TODO				obsolete
Arlequin.pyc			Homozygosity.pyc		Utils.py			popmeta
ChangeLog			MANIFEST.in			Utils.pyc			popmeta.py
DESIGN				Main.py				VERSION				pval
DEV_NOTES.md			Main.pyc			_EWSlatkinExactmodule.so	pypop
DataTypes.py			Meta.py				_Emhaplofreqmodule.so		pypop.py
DataTypes.pyc			NEWS				_Gthwemodule.so			reference
Filter.py			ParseFile.py			_Pvaluemodule.so		setup.cfg
Filter.pyc			ParseFile.pyc			build				setup.py
GUIApp.py			README.md			case-control.py			slatkin-exact
Haplo.py			RandomBinning.py		config.ini			unit-tests
Haplo.pyc			RandomBinning.pyc		data				xslt
HardyWeinberg.py		SWIG				emhaplofreq
HardyWeinberg.pyc		Singularity			gthwe
:pypop sjmack$

**Comment by alexlancaster** [comment]
```rm pypop```

Mac preserves case, but is case insensitive so it's confusing PyPop with pypop. Yes, it's weird and annoying.

**Comment by sjmack** [comment]
That worked! Thanks. You learn something new every day.

**Comment by sjmack** [comment]
So, I'm getting a number of warnings and an error trying to build in the module-refactor branch: 

:pypop sjmack$ ./setup.py build
running build
running build_py
creating build/lib.macosx-10.10-x86_64-2.7
creating build/lib.macosx-10.10-x86_64-2.7/PyPop
copying PyPop/__init__.py -> build/lib.macosx-10.10-x86_64-2.7/PyPop
copying PyPop/Arlequin.py -> build/lib.macosx-10.10-x86_64-2.7/PyPop
copying PyPop/DataTypes.py -> build/lib.macosx-10.10-x86_64-2.7/PyPop
copying PyPop/Filter.py -> build/lib.macosx-10.10-x86_64-2.7/PyPop
copying PyPop/GUIApp.py -> build/lib.macosx-10.10-x86_64-2.7/PyPop
copying PyPop/Haplo.py -> build/lib.macosx-10.10-x86_64-2.7/PyPop
copying PyPop/HardyWeinberg.py -> build/lib.macosx-10.10-x86_64-2.7/PyPop
copying PyPop/Homozygosity.py -> build/lib.macosx-10.10-x86_64-2.7/PyPop
copying PyPop/Main.py -> build/lib.macosx-10.10-x86_64-2.7/PyPop
copying PyPop/Meta.py -> build/lib.macosx-10.10-x86_64-2.7/PyPop
copying PyPop/ParseFile.py -> build/lib.macosx-10.10-x86_64-2.7/PyPop
copying PyPop/RandomBinning.py -> build/lib.macosx-10.10-x86_64-2.7/PyPop
copying PyPop/Utils.py -> build/lib.macosx-10.10-x86_64-2.7/PyPop
running build_ext
building '_Emhaplofreqmodule' extension
swigging emhaplofreq/emhaplofreq_wrap.i to emhaplofreq/emhaplofreq_wrap_wrap.c
swig -python -ISWIG -o emhaplofreq/emhaplofreq_wrap_wrap.c emhaplofreq/emhaplofreq_wrap.i
creating build/temp.macosx-10.10-x86_64-2.7
creating build/temp.macosx-10.10-x86_64-2.7/emhaplofreq
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -D__SWIG__=1 -DDEBUG=0 -DEXTERNAL_MODE=1 -DXML_OUTPUT=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Iemhaplofreq -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c emhaplofreq/emhaplofreq_wrap_wrap.c -o build/temp.macosx-10.10-x86_64-2.7/emhaplofreq/emhaplofreq_wrap_wrap.o
emhaplofreq/emhaplofreq_wrap_wrap.c:3408:17: warning: implicit declaration of function 'main_proc' is invalid in C99 [-Wimplicit-function-declaration]
  result = (int)main_proc(arg1,(char (*)[7*2][22])arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
                ^
emhaplofreq/emhaplofreq_wrap_wrap.c:3364:12: warning: variable 'arg2' is uninitialized when used here [-Wuninitialized]
      free(arg2);
           ^~~~
emhaplofreq/emhaplofreq_wrap_wrap.c:3258:24: note: initialize the variable 'arg2' to silence this warning
  char (*arg2)[7*2][22] ;
                       ^
                        = NULL
2 warnings generated.
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -D__SWIG__=1 -DDEBUG=0 -DEXTERNAL_MODE=1 -DXML_OUTPUT=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Iemhaplofreq -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c emhaplofreq/emhaplofreq.c -o build/temp.macosx-10.10-x86_64-2.7/emhaplofreq/emhaplofreq.o
/usr/bin/clang -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names -L/opt/local/lib/db48 build/temp.macosx-10.10-x86_64-2.7/emhaplofreq/emhaplofreq_wrap_wrap.o build/temp.macosx-10.10-x86_64-2.7/emhaplofreq/emhaplofreq.o -o build/lib.macosx-10.10-x86_64-2.7/_Emhaplofreqmodule.so
building '_EWSlatkinExactmodule' extension
swigging slatkin-exact/monte-carlo_wrap.i to slatkin-exact/monte-carlo_wrap_wrap.c
swig -python -ISWIG -o slatkin-exact/monte-carlo_wrap_wrap.c slatkin-exact/monte-carlo_wrap.i
creating build/temp.macosx-10.10-x86_64-2.7/slatkin-exact
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c slatkin-exact/monte-carlo_wrap_wrap.c -o build/temp.macosx-10.10-x86_64-2.7/slatkin-exact/monte-carlo_wrap_wrap.o
slatkin-exact/monte-carlo_wrap_wrap.c:3280:7: warning: variable 'arg1' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
  if (!PyArg_ParseTuple(args,(char *)"OOOO:main_proc",&obj0,&obj1,&obj2,&obj3)) SWIG_fail;
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
slatkin-exact/monte-carlo_wrap_wrap.c:3334:9: note: uninitialized use occurs here
    if (arg1)
        ^~~~
slatkin-exact/monte-carlo_wrap_wrap.c:3280:3: note: remove the 'if' if its condition is always false
  if (!PyArg_ParseTuple(args,(char *)"OOOO:main_proc",&obj0,&obj1,&obj2,&obj3)) SWIG_fail;
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
slatkin-exact/monte-carlo_wrap_wrap.c:3264:12: note: initialize the variable 'arg1' to silence this warning
  int *arg1 ;
           ^
            = NULL
1 warning generated.
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c slatkin-exact/monte-carlo.c -o build/temp.macosx-10.10-x86_64-2.7/slatkin-exact/monte-carlo.o
/usr/bin/clang -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names -L/opt/local/lib/db48 build/temp.macosx-10.10-x86_64-2.7/slatkin-exact/monte-carlo_wrap_wrap.o build/temp.macosx-10.10-x86_64-2.7/slatkin-exact/monte-carlo.o -o build/lib.macosx-10.10-x86_64-2.7/_EWSlatkinExactmodule.so
building '_Pvaluemodule' extension
swigging pval/pval_wrap.i to pval/pval_wrap_wrap.c
swig -python -ISWIG -o pval/pval_wrap_wrap.c pval/pval_wrap.i
creating build/temp.macosx-10.10-x86_64-2.7/pval
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/pval_wrap_wrap.c -o build/temp.macosx-10.10-x86_64-2.7/pval/pval_wrap_wrap.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/pval.c -o build/temp.macosx-10.10-x86_64-2.7/pval/pval.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/pchisq.c -o build/temp.macosx-10.10-x86_64-2.7/pval/pchisq.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/chebyshev.c -o build/temp.macosx-10.10-x86_64-2.7/pval/chebyshev.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/ftrunc.c -o build/temp.macosx-10.10-x86_64-2.7/pval/ftrunc.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/lgamma.c -o build/temp.macosx-10.10-x86_64-2.7/pval/lgamma.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/mlutils.c -o build/temp.macosx-10.10-x86_64-2.7/pval/mlutils.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/pgamma.c -o build/temp.macosx-10.10-x86_64-2.7/pval/pgamma.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/fmin2.c -o build/temp.macosx-10.10-x86_64-2.7/pval/fmin2.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/fmax2.c -o build/temp.macosx-10.10-x86_64-2.7/pval/fmax2.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/dnorm.c -o build/temp.macosx-10.10-x86_64-2.7/pval/dnorm.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/dpois.c -o build/temp.macosx-10.10-x86_64-2.7/pval/dpois.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/gamma.c -o build/temp.macosx-10.10-x86_64-2.7/pval/gamma.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/bd0.c -o build/temp.macosx-10.10-x86_64-2.7/pval/bd0.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/stirlerr.c -o build/temp.macosx-10.10-x86_64-2.7/pval/stirlerr.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/lgammacor.c -o build/temp.macosx-10.10-x86_64-2.7/pval/lgammacor.o
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMATHLIB_STANDALONE=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Ipval -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pval/pnorm.c -o build/temp.macosx-10.10-x86_64-2.7/pval/pnorm.o
/usr/bin/clang -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names -L/opt/local/lib/db48 build/temp.macosx-10.10-x86_64-2.7/pval/pval_wrap_wrap.o build/temp.macosx-10.10-x86_64-2.7/pval/pval.o build/temp.macosx-10.10-x86_64-2.7/pval/pchisq.o build/temp.macosx-10.10-x86_64-2.7/pval/chebyshev.o build/temp.macosx-10.10-x86_64-2.7/pval/ftrunc.o build/temp.macosx-10.10-x86_64-2.7/pval/lgamma.o build/temp.macosx-10.10-x86_64-2.7/pval/mlutils.o build/temp.macosx-10.10-x86_64-2.7/pval/pgamma.o build/temp.macosx-10.10-x86_64-2.7/pval/fmin2.o build/temp.macosx-10.10-x86_64-2.7/pval/fmax2.o build/temp.macosx-10.10-x86_64-2.7/pval/dnorm.o build/temp.macosx-10.10-x86_64-2.7/pval/dpois.o build/temp.macosx-10.10-x86_64-2.7/pval/gamma.o build/temp.macosx-10.10-x86_64-2.7/pval/bd0.o build/temp.macosx-10.10-x86_64-2.7/pval/stirlerr.o build/temp.macosx-10.10-x86_64-2.7/pval/lgammacor.o build/temp.macosx-10.10-x86_64-2.7/pval/pnorm.o -o build/lib.macosx-10.10-x86_64-2.7/_Pvaluemodule.so
building '_Gthwemodule' extension
swigging gthwe/gthwe_wrap.i to gthwe/gthwe_wrap_wrap.c
swig -python -ISWIG -o gthwe/gthwe_wrap_wrap.c gthwe/gthwe_wrap.i
creating build/temp.macosx-10.10-x86_64-2.7/gthwe
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -D__SWIG__=1 -DDEBUG=0 -DXML_OUTPUT=1 -DSUPPRESS_ALLELE_TABLE=1 -DINDIVID_GENOTYPES=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Igthwe -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c gthwe/gthwe_wrap_wrap.c -o build/temp.macosx-10.10-x86_64-2.7/gthwe/gthwe_wrap_wrap.o
gthwe/gthwe_wrap_wrap.c:3424:7: warning: variable 'arg2' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
  if (!PyArg_ParseTuple(args,(char *)"OOOOOOOOOO:run_data",&obj0,&obj1,&obj2,&obj3,&obj4,&obj5,&obj6,&obj7,&obj8,&obj9)) SWIG_fail;
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gthwe/gthwe_wrap_wrap.c:3552:9: note: uninitialized use occurs here
    if (arg2)
        ^~~~
gthwe/gthwe_wrap_wrap.c:3424:3: note: remove the 'if' if its condition is always false
  if (!PyArg_ParseTuple(args,(char *)"OOOOOOOOOO:run_data",&obj0,&obj1,&obj2,&obj3,&obj4,&obj5,&obj6,&obj7,&obj8,&obj9)) SWIG_fail;
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gthwe/gthwe_wrap_wrap.c:3388:12: note: initialize the variable 'arg2' to silence this warning
  int *arg2 ;
           ^
            = NULL
gthwe/gthwe_wrap_wrap.c:3424:7: warning: variable 'arg1' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
  if (!PyArg_ParseTuple(args,(char *)"OOOOOOOOOO:run_data",&obj0,&obj1,&obj2,&obj3,&obj4,&obj5,&obj6,&obj7,&obj8,&obj9)) SWIG_fail;
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gthwe/gthwe_wrap_wrap.c:3548:9: note: uninitialized use occurs here
    if (arg1)
        ^~~~
gthwe/gthwe_wrap_wrap.c:3424:3: note: remove the 'if' if its condition is always false
  if (!PyArg_ParseTuple(args,(char *)"OOOOOOOOOO:run_data",&obj0,&obj1,&obj2,&obj3,&obj4,&obj5,&obj6,&obj7,&obj8,&obj9)) SWIG_fail;
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gthwe/gthwe_wrap_wrap.c:3387:12: note: initialize the variable 'arg1' to silence this warning
  int *arg1 ;
           ^
            = NULL
gthwe/gthwe_wrap_wrap.c:3586:7: warning: variable 'arg2' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
  if (!PyArg_ParseTuple(args,(char *)"OOOOOOO:run_randomization",&obj0,&obj1,&obj2,&obj3,&obj4,&obj5,&obj6)) SWIG_fail;
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gthwe/gthwe_wrap_wrap.c:3698:9: note: uninitialized use occurs here
    if (arg2)
        ^~~~
gthwe/gthwe_wrap_wrap.c:3586:3: note: remove the 'if' if its condition is always false
  if (!PyArg_ParseTuple(args,(char *)"OOOOOOO:run_randomization",&obj0,&obj1,&obj2,&obj3,&obj4,&obj5,&obj6)) SWIG_fail;
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gthwe/gthwe_wrap_wrap.c:3563:12: note: initialize the variable 'arg2' to silence this warning
  int *arg2 ;
           ^
            = NULL
gthwe/gthwe_wrap_wrap.c:3586:7: warning: variable 'arg1' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
  if (!PyArg_ParseTuple(args,(char *)"OOOOOOO:run_randomization",&obj0,&obj1,&obj2,&obj3,&obj4,&obj5,&obj6)) SWIG_fail;
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gthwe/gthwe_wrap_wrap.c:3694:9: note: uninitialized use occurs here
    if (arg1)
        ^~~~
gthwe/gthwe_wrap_wrap.c:3586:3: note: remove the 'if' if its condition is always false
  if (!PyArg_ParseTuple(args,(char *)"OOOOOOO:run_randomization",&obj0,&obj1,&obj2,&obj3,&obj4,&obj5,&obj6)) SWIG_fail;
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gthwe/gthwe_wrap_wrap.c:3562:12: note: initialize the variable 'arg1' to silence this warning
  int *arg1 ;
           ^
            = NULL
4 warnings generated.
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -D__SWIG__=1 -DDEBUG=0 -DXML_OUTPUT=1 -DSUPPRESS_ALLELE_TABLE=1 -DINDIVID_GENOTYPES=1 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include -Igthwe -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c gthwe/hwe.c -o build/temp.macosx-10.10-x86_64-2.7/gthwe/hwe.o
In file included from gthwe/hwe.c:49:
gthwe/hwe.h:50:10: fatal error: 'gsl/gsl_rng.h' file not found
#include <gsl/gsl_rng.h>
         ^
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1

**Comment by alexlancaster** [comment]
Could you perhaps remove the entire directory and re-check out out of github?  e.g.

```
git clone .... (as you did the first time)
git checkout module-refactor
```

It's possible it's something to do with the old build hanging around.

**Comment by alexlancaster** [comment]
Also, it looks like it's failing on finding the header files for libraries:

1. what is the result of:

```
echo $CPATH
echo $LIBRARY_PATH
echo $PATH
```
2. check that MacPorts gsl is properly installed 

```port installed``` 

should show the ```gsl``` library somewhere

**Comment by sjmack** [comment]
so I don't seem to have a CPATH, although I have gcc installed, and it built the master branch fine:

:pypop sjmack$ echo $PATH
/opt/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/opt/X11/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/opt/X11/bin
:pypop sjmack$ echo $CPATH

:pypop sjmack$ echo $LIBRARY_PATH
/usr/lib:/usr/local/lib:

> port installed

 shows  

> gsl @2.2.1_0 (active)

**Comment by alexlancaster** [comment]
Odd that it worked for master, could have been that when you compiled it you had set it temporarily.  Either way you should set it in your ~/.bash_profile as per item 3 on https://github.com/alexlancaster/pypop/blob/master/README.md#macos-x

**Comment by alexlancaster** [comment]
@gwebster verified that branch worked on his system, merging to master.

**Pull request merged**
