### PR TITLE
Remove/numeric, update to python 3.0

### PR DESCRIPTION
**Pull request by vsoch**
hey @alexlancaster, long time no chat! I was poking around your code (huge +1 for container-izing this beast, btw) and noticed that you are still using Python 2.(something) and Numeric (instead of Numpy). What I've done is (most) of the annoying work to convert from Python 2, and most of removing Numeric. The main changes are the following:

 - the obvious print "hello" to print("hello")
 - removal of string, I don't think I've ever seen that used before! lol
 - permissions for os.chmod are usually a proper mode from the stat module
 - StringIO and all its friends are now in the io module

The Singularity build file is updated so the libraries compile and the image builds (run `build-singularity.sh` to do start to finish, albeit you will notice warnings from the compile about undeclared things.  There is a lot here to discuss (the code needs a lot of work) but I think if we all work together and come up with a plan, this will be reasonable to do. I stopped at the point where the (c compiled modules) were giving me bugs - I've never used swig before and would need to learn a bit. Thus - this isn't a full working PR. However, I think the following would be helpful to that about.

 - what of the C functions are necessary to include, and aren't do-able in Python? For example, is it necessary to have a function in C to calculate a pvalue? If we can remove some of these, that would be great. For those we can't, then we might want to clean up the setup.py a bit. For example, instead of a file called version for versioning I typically have a version.py ([example](https://github.com/pydicom/deid/blob/master/deid/version.py)) that then populates setup.py ([example](https://github.com/pydicom/deid/blob/master/setup.py))
 - reorganization of these functions is totally paramount.
 - instead of carrying around a variable for debug (eg self.debug) using python logging will make it really easy to specify prints at different levels, and not need to do these checks.
 - testing, meaning testing with continuous integration, is totally essential. There were bugs that I ran across that I don't think would happen if there were tests! I make a TON of mistakes and I would be a total wreck without something continually testing my additions/subtractions.

The general goal should be to reduce the number of dependencies - meaning thinking of the cleanest way to achieve some function, have good code coverage for testing, and having a code base that is intuitively organized, documented, and easy to follow. Then for usage, it should be trivial to just run a Docker or Singularity image. The final thing will be great!! Let me know your thoughts.

I love the name, btw! py:popcorn: py:popcorn:

### CODE REVIEW

**Comment by akkornel** [comment]
Hello!

I just wanted to note, in advance of our call on Friday, that I'm in support of containerization here.

I mentioned Singularity in an email conversation with you several weeks ago; @vsoch is one of the developers on Singularity; she's also the lead on Singularity Hub.

The servers where PyPop will be running are part of a cluster that is being used for workshop data ingest.  That means that the operating environment of those servers is essentially set in stone until the workshop wraps up.  Of course, Lisa and @kosoegawa still want PyPop development to continue.  Hence the need for containerization!  It will be much easier on Lisa in particular if you can just provide a container and say "Here, this container has code changes; try it and let us know the results!"

I've been able to bootstrap PyPop into a Singularity container by hand, but doing so in an automated way has had issues.  @vsoch came in earlier today to help with this, and started to go on a general cleanup as a result.  So, please have a look, we'll talk soon!

**Comment by alexlancaster** [comment]
Hi Vanessa! Small world! Thanks for the PR and thanks to Karl for the background on containerization. Will chime in with more details soon.

**Comment by alexlancaster** [comment]
Hi @vsoch I checked out the PR, thanks again!  This is awesome.  At this time, we're on a tight timeline to implement some new features, so we don't want to do a switch to Python 3 and numpy right away (as way of a bit of a background the code was mostly written between 2003-2005 and hasn't had any updates since about 2008/09, hence the old deps).  

However, once we have these features/fixes working nicely (and part of this update is creating the test suite you mention), then we plan to switch to numarray, time permitting (you'll see I already filed the issue #2 to myself).

If you would be willing, it would be really helpful for us if you could break your PR up into three separate PRs, along these lines:

1. update to Python 3.x
2. update to numpy
3. all updates that aren't either of the above kinds

We would then be able to apply them in reverse order.  Also, the branch "modules-refactor" is about to become "master": it does a number of code reorganizations, including updating to use setuptools etc. so you might want rebase against that.

Thanks again for your interest!

**Comment by vsoch** [comment]
Hey @alexlancaster ! I'm glad to hear about (and see!) the re-organization (it is SO much better). I think the changes to get to numpy are pretty trivial, and you probably can get most of the conversion done with a test run of [https://docs.python.org/2/library/2to3.html](https://docs.python.org/2/library/2to3.html) as opposed to what I did, which was manually going through and making changes (I'm not a fan of automated things although I'm sure if you just do things like prints, it's a tool well worth it). I can't offer huge time in the way of services because I just don't have it. I will, however, always step in to help @akkornel. He's awesome, btw :)

I would encourage you to **prioritize** moving away from Numeric (eg, I'm seeing label "Nice to Have") milestone which coincides with "If there is ever a rainy day and I have absolutely nothing to do" (never happens :P)  

Numeric has dependencies that even make the installation / host environment really hard to build a container (the reason I had done the PR in the first place was because @akkornel was having a hard time putting this monster in a container) If there is a dependency on Numeric, then there is also a dependency on using a particular base OS that still provides it. This means Fedora, which then means generating the container is much more buggy due to Fedora's (in the container) and the host needing to share the same modules for the package manager. Trying to build your container is a hairball mess because of this, but if you don't have the container, then your users are going to have to go through the pain of installing dependencies themselves.

What's the problem with that? Running scientific workflows is getting a lot easier thanks to containers, and you can think of a person's attention span for "getting something to work" akin to their attention span for perusing a website, If you go on a site and find what you want, and it looks good, you are happy. If you go to a site and it doesn't seem good within 10-15 seconds, you click away. Just doing a quick search on BioContainers, here are your competitors:

image

So if your goal is truly to allow others to use this, and you are an advocate for reproducible science, I would advocate for making this module as easy to install (and thus create a container for) and use. I don't see this being the case currently.

**Comment by alexlancaster** [comment]
Hi Vanessa, removing Numeric for all the reasons you suggest is definitely on our major TODO list!  Thanks, Alex

**Comment by alexlancaster** [comment]
Manually merged a modified version of this PR into upstream [python3](https://github.com/alexlancaster/pypop/tree/python3) branch.  Thanks @vsoch .

**Comment by vsoch** [comment]
Awesome thanks! I hope my code from back then isn’t too terrible (I’m pretty sure it was… 😆). Hope you are well!

**Pull request closed without merging**
