### PR TITLE
changed GENOTYPE_TERMINATOR to "~" (from "|") in emhaplofreq.c & PyPop/Haplo.py

### PR DESCRIPTION
**Pull request by rsingle**
LD calcs were not working correctly with different values for GENOTYPE_TERMINATOR & GENOTYPE_SEPARATOR. Both are now set to "~"

### CODE REVIEW

**Comment by alexlancaster** [comment]
This is great.  I think all we need now is to fix the unit tests:

- update the md5sum for the `test_AlleleColon_Emhaplofreq` test for the new (correct) output
- update the gold output file for the `test_USAFEL_slatkin_guothompson_emhaplofreq` in [`tests/data/output/USAFEL-UchiTelle-small-out.txt`](https://github.com/alexlancaster/pypop/blob/master/tests/data/output/USAFEL-UchiTelle-small-out.txt)

**Review by alexlancaster — COMMENTED** [review]
This is great.  I think all we need now is to fix the unit tests:

- update the md5sum for the `test_AlleleColon_Emhaplofreq` test for the new (correct) output
- update the gold output file for the `test_USAFEL_slatkin_guothompson_emhaplofreq` in [`tests/data/output/USAFEL-UchiTelle-small-out.txt`](https://github.com/alexlancaster/pypop/blob/master/tests/data/output/USAFEL-UchiTelle-small-out.txt)

**Review by alexlancaster — COMMENTED** [review]
Almost!  Looking at the log when testing the wheels, it looks like there is still missing the change in the loglikehood value, see:

https://github.com/alexlancaster/pypop/actions/runs/4168578724/jobs/7215543499#step:3:435

**Review by alexlancaster — COMMENTED** [review]
Looks like this now passes: https://github.com/alexlancaster/pypop/actions/runs/4168578724/jobs/7215543499#step:3:402

**Comment by alexlancaster** [comment]
Once this is merged upstream, it should hopefully fix open issue #40 .

**Review by alexlancaster — COMMENTED** [review]
it's odd, this works OK on Linux ([Linux log](https://github.com/alexlancaster/pypop/actions/runs/4168708449/jobs/7215829327#step:3:429)), but the macos build fails because it generates `nan`, not `-nan` ([macos log](https://github.com/alexlancaster/pypop/actions/runs/4168708449/jobs/7215829422#step:3:277)) this may because of platform-specific represention of nan.

**Review by alexlancaster — COMMENTED** [review]
my quick fix to the stylesheets don't quite work for all cases.  I think the right place to fix this is within `emhaplofreq.c`:  when we compute `summary_d`, `summary_dprime`, `summary_wn`, or any place where there is potential division by zero we need to handle catch that and output a predictable string, whether than is `0.000` or `nan`.  fixing the output is too fragile.

**Review by alexlancaster — APPROVED** [review]
great - this works and unit test and build checks work!

**Comment by rsingle** [comment]
> great - this works and unit test and build checks work! I'll merge the PR and close

Wooo-Hooo!

**Pull request merged**
