### PR TITLE
Update ALD calculations in `emhaplofreq` and unit tests

### PR DESCRIPTION
**Pull request by rsingle**

### CODE REVIEW

**Comment by alexlancaster** [comment]
This is close to passing the tests but looks like the md5sum is slightly off?

https://github.com/alexlancaster/pypop/actions/runs/5336215276/jobs/9670568475#step:3:434

I'm wondering if this is because it's from a pypop run from the command line outside the test harness?

**Comment by alexlancaster** [comment]
Oh I realize what's happened. Because I had to revert the upstream main branch, the original changes you made to emhaplofreq have been lost from your ALD branch. You'll see this if you look at the changes to the files relative to main, there's only the allele count change. You'll need to also reapply those original changes back to your branch which will update the PR and rerun the unit tests.

**Comment by alexlancaster** [comment]
Essentially this pull request replaces the original pull request because I had to revert those changes.

**Comment by rsingle** [comment]
I reinstated the changes for ALD calcs in emhaplofreq.c and the output files for the tests

**Comment by alexlancaster** [comment]
> Success!

Nice!  I'm just quickly reviewing the code and tests and I'll go and and merge in a bit.  Thanks @rsingle !

**Review by alexlancaster — COMMENTED** [review]
Looks excellent!  I'll squash merge in a sec.

**Pull request merged**
