### PR TITLE
ALD emhaplofreq

### PR DESCRIPTION
**Pull request by alexlancaster**
@rsingle This will probably require adjustments to unit tests before merging.

### CODE REVIEW

**Comment by rsingle** [comment]
I'll work on the unit tests asap.

**Comment by rsingle** [comment]
ALD unit tests are updated

**Comment by alexlancaster** [comment]
Looking at the build failures, as I suspected, it looks like the other `emhaplofreq` tests also need to be updated:

https://github.com/alexlancaster/pypop/actions/runs/5328415581/jobs/9652993928#step:3:284

**Comment by alexlancaster** [comment]
this is not yet ready to merge, so I am reverting.  that should only be merged to `main` once all tests pass

**Comment by rsingle** [comment]
OK. I'll work on those tomorrow.

**Comment by alexlancaster** [comment]
thanks, once the tests pass, just leave it and I'll manage the merge part, it's a bit tricky because I need to rebase the other branches after it's merged into main.

**Pull request merged**
