### PR TITLE
Port PyPop to Numpy

### PR DESCRIPTION
**Pull request by alexlancaster**
I have a preliminary port from ```Numeric``` to ```numpy``` (#2).   This should make it a lot easier to build, package for PyPI and maintain going forward.  I've also updated the Singularity build script accordingly.  @akkornel & @vsoch, please do give it whirl and see if it builds for you.

@sjmack: please do also try this branch and see if all your files still work.  You'll need to use MacPorts to add the ```py27-numpy``` dependency (this is described in the README.md):

     sudo port install py27-numpy

Then switch to this branch and rebuild:

     git checkout numpy-port
     ./setup.py clean --all
     ./setup.py build

I've run everything through our current test suite and it all seems to be work, but with a major dependency change, would be good to have as many runs as possible.

### CODE REVIEW

**Comment by sjmack** [comment]
py.test performed fine: 11 passed, 1 skipped in 70.25 seconds

Results for `./bin/pypop.py -c WS_20loci_HW.ini Synth_PyPop_Dataset.pop`,  `./bin/pypop.py -c WS_BDCtrl_Test_EM.ini BIGDAWG_SynthControl_Data.pop`  and `./bin/pypop.py -c WS_BDCtrl_Test_HW.ini BIGDAWG_SynthControl_Data.pop` look consistent with previous results.

**Comment by vsoch** [comment]
hey @alexlancaster great news! 

I built a basic image to test using the following build recipe:

```
Bootstrap: docker
From: continuumio/miniconda

%post

    apt-get update && apt-get install -y swig gcc wget build-essential vim git
    /opt/conda/bin/conda install -y numpy pytest

    cd /opt
    wget https://ftp.gnu.org/gnu/gsl/gsl-2.4.tar.gz
    tar -xzvf gsl-2.4.tar.gz
    cd gsl-2.4
    ./configure --prefix=/usr/local
    make
    make install
    ldconfig

    # Install pypop
    cd /opt
    git clone -b numpy-port https://github.com/alexlancaster/pypop.git
    cd /opt/pypop
    /opt/conda/bin/python setup.py build
    /opt/conda/bin/python setup.py install
    ldconfig

%runscript

    exec /opt/conda/bin/pypop.py $@

%test

    cd /opt/pypop
    python -m unittest discover tests
```
and commands:

```
singularity create --size 3000 pypop.img
sudo singularity bootstrap pypop.img Singularity 
```

the build works ok, and I want to suggest that there is a more clear outline for the testing - I've been futzing around with different testing commands (even the ones linked above) and I'm not familiar with the software, but it seems to require some config. My suggestion is the following:

 - setup tests to run automatically on travis or circle CI
 - then I can reproduce those tests with the container, and we confirm it works as expected

**Comment by alexlancaster** [comment]
It uses pytest.

**Comment by vsoch** [comment]
haha, yes I gleaned that :) I need to be able to reproduce the testing in the container. The commands here and in other places failed tests for me. It would be good for the codebase to add automated testing with CI.

**Comment by alexlancaster** [comment]
What happens  if you use py.test in the ```%test``` stanza?

    %test
        cd /opt/pypop
        py.test

**Comment by alexlancaster** [comment]
@rsingle verified this worked on Ubuntu. closing.

**Comment by vsoch** [comment]
:/

**Comment by vsoch** [comment]
```
py.test tests
=========================================================== test session starts ===========================================================
platform linux2 -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0
rootdir: /opt/pypop, inifile:
collected 12 items 

tests/test_AlleleColon.py FF
tests/test_GenotypeCommon.py FF
tests/test_StringMatrix.py .......
tests/test_gthwe.py s

================================================================ FAILURES =================================================================
_____________________________________________________ test_AlleleColon_HardyWeinberg ______________________________________________________

    def test_AlleleColon_HardyWeinberg():
        exit_code = base.run_pypop_process('./tests/data/Test_Allele_Colon_HardyWeinberg.ini', './tests/data/Test_Allele_Colon_HardyWeinberg.pop')
        # check exit code
>       assert exit_code == 0
E       assert 1 == 0

tests/test_AlleleColon.py:9: AssertionError
______________________________________________________ test_AlleleColon_Emhaplofreq _______________________________________________________

    def test_AlleleColon_Emhaplofreq():
    
        exit_code = base.run_pypop_process('./tests/data/Test_Allele_Colon_Emhaplofreq.ini', './tests/data/Test_Allele_Colon_Emhaplofreq.pop')
        # check exit code
>       assert exit_code == 0
E       assert 1 == 0

tests/test_AlleleColon.py:17: AssertionError
____________________________________________________ test_GenotypeCommon_HardyWeinberg ____________________________________________________

    def test_GenotypeCommon_HardyWeinberg():
        exit_code = base.run_pypop_process('./tests/data/WS_BDCtrl_Test_HW.ini', './tests/data/BIGDAWG_SynthControl_Data.pop')
        # check exit code
>       assert exit_code == 0
E       assert 1 == 0

tests/test_GenotypeCommon.py:9: AssertionError
__________________________________________________ test_GenotypeCommonDash_HardyWeinberg __________________________________________________

    def test_GenotypeCommonDash_HardyWeinberg():
        exit_code = base.run_pypop_process('./tests/data/WS_BDCtrl_Test_HW.ini', './tests/data/BIGDAWG_SynthControl_Data_dash.pop')
        # check exit code
>       assert exit_code == 0
E       assert 1 == 0

tests/test_GenotypeCommon.py:16: AssertionError
============================================= 4 failed, 7 passed, 1 skipped in 100.71 seconds =============================================
Singularity pypop.img:/opt/pypop> ls tests/data/
```

**Comment by vsoch** [comment]
Here is an example [travis.yml](https://github.com/pydicom/pydicom/blob/master/.travis.yml) that you could easily add to test on every PR, with tweaks for the dependencies that you need. I think minimally this should be working in a container, so users of your software don't have to deal with the dependencies. Continuous integration with tests and a provided container are sort of the "minimal recipe" for reproducible open source software.

**Comment by alexlancaster** [comment]
Ah, you need to run ```py.test``` from within the checkout, not from the installed version.

**Comment by vsoch** [comment]
What do you mean? I used the `numpy-port` branch that was from this PR:

```
git clone -b numpy-port https://github.com/alexlancaster/pypop.git
```

**Comment by alexlancaster** [comment]
Odd. Dunno, try doing it outside the container for the moment.  (Anyway it's all merged back to master now).

**Comment by vsoch** [comment]
:/

**Comment by alexlancaster** [comment]
Good idea, I'll look into travis.

**Pull request merged**
